version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: '{{ .ProjectName }}'
checksum:
  name_template: '{{ .ProjectName }}_SHA256SUMS'
  algorithm: sha256
changelog:
  disable: false

docker_manifests:
  - name_template: "ghcr.io/yamamoto-febc/otlp-http-spy:{{ .Version }}"
    image_templates:
      - "ghcr.io/yamamoto-febc/otlp-http-spy:{{ .Version }}-amd64"
      - "ghcr.io/yamamoto-febc/otlp-http-spy:{{ .Version }}-arm64"
  - name_template: "ghcr.io/yamamoto-febc/otlp-http-spy:latest"
    image_templates:
      - "ghcr.io/yamamoto-febc/otlp-http-spy:latest-amd64"
      - "ghcr.io/yamamoto-febc/otlp-http-spy:latest-arm64"

dockers:
  - image_templates:
      - "ghcr.io/yamamoto-febc/otlp-http-spy:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/yamamoto-febc/otlp-http-spy:{{ .Version }}-arm64"
    use: buildx
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/arm64"
  - image_templates:
      - "ghcr.io/yamamoto-febc/otlp-http-spy:latest-amd64"
    use: buildx
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/yamamoto-febc/otlp-http-spy:latest-arm64"
    use: buildx
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/arm64"
